services:
  cert-gen:
    build:
      context: .
    volumes:
      - ./certs:/app/certs
      - ./generate-certs.sh:/app/generate-certs.sh
    entrypoint: "sh /app/generate-certs.sh"

  socat-server:
    build:
      context: .
    depends_on:
      - cert-gen
      - nginx-server
    volumes:
      - ./certs:/app/certs
    ports:
      - "12345:12345"
    command: >
      socat -v
      OPENSSL-LISTEN:12345,reuseaddr,fork,cert=/app/certs/server.crt,key=/app/certs/server.key,verify=0
      OPENSSL:nginx-server:443,cert=/app/certs/client.crt,key=/app/certs/client.key,cafile=/app/certs/ca.crt,verify=1

  fastapi:
    build:
      dockerfile: ../fastapi.Dockerfile
      context: ./app
    expose:
      - "8000" # Internal network port

  nginx-server:
    image: nginx:1.14.1
    depends_on:
      - cert-gen
      - fastapi
    volumes:
      - ./certs:/app/certs
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "443:443"
    command: nginx -g "daemon off;"

  curl-tester:
    image: curlimages/curl:latest
    restart: always
    depends_on:
      - nginx-server
    volumes:
      - ./certs:/app/certs
    command: >
      sh -c "curl --cert /app/certs/client.crt --key /app/certs/client.key --cacert /app/certs/ca.crt https://nginx-server &&
      sleep 60"

  socat-tester:
    image: curlimages/curl:latest
    restart: always
    depends_on:
      - socat-server
    command: >
      sh -c "echo 'Testing socat server without certs using curl' && \
      curl --insecure https://socat-server:12345 && \
      sleep 60"

  mapi-mtls:
    build:
      context: .
      dockerfile: mapi.Dockerfile
    restart: always
    environment:
      - MAYHEM_URL=https://app.mayhem.security
      - MAYHEM_TOKEN=${MAYHEM_TOKEN}
    depends_on:
      - nginx-server
    volumes:
      - ./certs:/app/certs
    command: >
      sh -c "echo 'Running Mayhem for API tests using mTLS support...' && \
      mapi run 'mapi-action-examples/fastapi' auto https://nginx-server/openapi.json --url 'https://nginx-server/' --key /app/certs/client.key --cert /app/certs/client.crt --cacert /app/certs/ca.crt ; \
      sleep 60"

  mapi-socat:
    build:
      context: .
      dockerfile: mapi.Dockerfile
    restart: always
    environment:
      - MAYHEM_URL=https://app.mayhem.security
      - MAYHEM_TOKEN=${MAYHEM_TOKEN}
    depends_on:
      - socat-server
    volumes:
      - ./certs:/app/certs
    command: >
      sh -c "echo 'Running Mayhem for API tests via socat...' && \
      mapi run 'mapi-action-examples/fastapi' auto https://socat-server:12345/openapi.json --url 'https://socat-server:12345' --insecure-target; \
      sleep 60"
